name = "RadonKA"
uuid = "86de8297-835b-47df-b249-c04e8db91db5"
authors = ["Felix Wechsler (roflmaostc) <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IndexFunArrays = "613c443e-d742-454e-bfc6-1d7f8dd76566"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
Atomix = "0.1"
FFTW = "1.7"
julia = "1.9"
KernelAbstractions = "0.9"
IndexFunArrays = "0.2"



[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
